name: Container Image Build
on:
  push:
    branches:
      - master
      - build/*
jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      image-sha: ${{ steps.build.outputs.image-sha }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Log in to Red Hat Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REGISTRY_REDHAT_IO_USER }}
          password: ${{ secrets.REGISTRY_REDHAT_IO_PASSWORD }}

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: build-image
        name: Build Image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{github.repository}}
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile
      - name: Echo Outputs
        run: |
          echo "Image: ${{ steps.build-image.outputs.image }}"
          echo "Tags: ${{ steps.build-image.outputs.tags }}"
          echo "Tagged Image: ${{ steps.build-image.outputs.image-with-tag }}"
      - name: Push to GitHub Container Repository
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image-sha }}
          tags: ghcr.io/${{github.repository}}:latest