name: Container Image Build
on:
  push:
    branches:
      - master
jobs:
  build-image:
    runs-on: ubuntu-latest
    container:
      image: docker://registry.redhat.io/ubi8/buildah:latest
      credentials:
        username: ${{ secrets.REGISTRY_REDHAT_IO_USER }}
        password: ${{ secrets.REGISTRY_REDHAT_IO_PASSWORD }}
    outputs:
      image-sha: ${{ steps.build.outputs.image-sha }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - id: build
        name: Build image
        run: |
          buildah login registry.redhat.io -u ${{ secrets.REGISTRY_REDHAT_IO_USER }} -p ${{ secrets.REGISTRY_REDHAT_IO_PASSWORD }}
          buildah login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          chmod +x ./*.sh
          ./build.sh
          echo "::set-output name=image-sha::$(cat image.sha256)"
          buildah tag $(cat image.sha256) ghcr.io/${{github.repository}}:latest

      - name: Push to GitHub Container Repository
        id: push-to-ghcr
        run: buildah push ghcr.io/${{github.repository}}:latest